### PR TITLE
new domains from https://mail-temp.com/

### PR DESCRIPTION
**Pull request by ornicar**
these can't be extracted with `html_re`
because each page load gives a new batch.

### CODE REVIEW

**Comment by ornicar** [comment]
I pasted this in the browser console to extract domains: `$('#newselect .tt-suggestion p').toArray().map(o => o.id).join('\n')`

**Comment by Taytay** [comment]
Thanks @ornicar. 
@andreis : Any objections to merging this in?

**Comment by andreis** [comment]
@andreis no looks 👍

**Comment by smeinecke** [comment]
Add parser for the given host.

**Pull request closed without merging**
