### PR TITLE
Add new Domain to blacklist

### PR DESCRIPTION
**Pull request by AByGCreation**
Hello @andreis, I add "oolloo.org" to the blacklist domain.
Thanks for your service !

### CODE REVIEW

**Comment by smeinecke** [comment]
Thank you for your request. Could you please provide a source for this Domain so we can add them automatically?

**Comment by AByGCreation** [comment]
Sure, you've right
Here the website -> https://www.fakemail.net/

**Comment by Alex93klik93** [comment]
https://www.temp-mails.com/
@marmaryta.club
@marmaryta.email
@marmaryta.space
@marmaryta.life

**Comment by smeinecke** [comment]
Added to parser.

**Pull request closed without merging**
