### PR TITLE
Update blacklist.txt

### PR DESCRIPTION
**Pull request by tuptuptuu**
Add hey.com, disposable email provider.

Hey.com offers disposable email addresses in their iOS app.
0EA493AF-608A-4A60-B975-B352367B3976

### CODE REVIEW

**Comment by dhh** [comment]
This is a complete misnomer. HEY is a new email service with over 150,000 users and thousands of paying accounts. There is a separate service mandated by Apple that uses a specific 12 digit email address in the form of ####-####-#### that can be used for 14 days. You could create a similar address for a similar purpose on Gmail or any other service. These addresses are heavily limited and scrutinized to prevent abuse. Please revert this PR. You can find more information about HEY on https://hey.com. Thank you.

**Comment by dhh** [comment]
This user has been created solely for the harassment of HEY. See the rejection in other similar repos: https://github.com/ivolo/disposable-email-domains/pull/825

**Comment by troytoman** [comment]
From the hey.com team here. It is true that we offer a disposable option, these can only signed up for on the iOS app and they represent a small fraction of our users. Every disposable address is 12 digits separated by dashes. So you can ID them with the pattern ####-####-####@hey.com. We intend to eventually put them on a sub domain but can’t commit to a time.

**Comment by tuptuptuu** [comment]
@dhh So how many of those 150000 addresses will still be working after 2 weeks? Presumably only the “thousands of paying accounts”.

> You could create a similar address for a similar purpose on Gmail or any other service. 
At least those addresses don’t expire. Gmail has very strong anti-abuse measures, from behavioural analysis to phone verifications. 

I had no trouble creating a disposable hey.com addressusing an OVH datacenter IP and a fake email address. You don’t even verify the secondary email you ask for.

> These addresses are heavily limited and scrutinized to prevent abuse.
Couls you explain exactly how this is supposed to work? You haven’t even bothered to add email or phone verification, are you just talking about ratelimiting?

**Comment by tuptuptuu** [comment]
> This user has been created solely for the harassment of HEY
Don’t you think you’re going a bit too far with this? You offer disposable addresses on this domain, of course you’ll be added to DEA provider lists. 

There’s an easy solution available to you, just disable this feature until you can put these accounts on a different domain.

**Comment by tuptuptuu** [comment]
@smeinecke Why revert this? This should be solved by hey.com ceasing to offer disposable emails or moving them over to another domain, not by excluding them from DEA lists until they do so.

**Comment by smeinecke** [comment]
@tuptuptuu many other providers (like gmx, mail.com and even gmail) have the same feature - should I add them as well?

**Comment by tuptuptuu** [comment]
> @tuptuptuu many other providers (like gmx, mail.com and even gmail) have the same feature - should I add them as well?

None of those offer expiring randomly generated addresses.

**Comment by Phillipus** [comment]
> This user has been created solely for the harassment of HEY. See the rejection in other similar repos: [ivolo/disposable-email-domains#825](https://github.com/ivolo/disposable-email-domains/pull/825)

+1 on this. 

The account of @tuptuptuu has been created solely to harass HEY based on a petty personal grudge. Suggest reverting this bogus PR.

**Comment by fm** [comment]
@Phillipus It's been reverted, and to add a cherry on the cake, hey.com was added to the whitelist https://github.com/andreis/disposable/commit/f72e4e23e127695bcaea61d88519db56c2bc06ca

**Comment by erkanercan** [comment]
Wow, @smeinecke made a good decision.

**Pull request merged**
